"""Read-only integration boundary for pinned public KB contracts.

This package never imports the provider package or discovers a sibling
checkout. Callers must supply an InvestSystem-owned, hash-verified snapshot.
"""

from .contracts import (
    ContractSnapshotError,
    ContractValidationError,
    KBContractCatalog,
    SnapshotIntegrityError,
    StrictJsonError,
    load_kb_contract_snapshot,
    load_strict_json_bytes,
)
from .export_package import (
    ExportValidationCode,
    ImmutableExportValidationError,
    VerifiedExportMember,
    VerifiedImmutableExport,
    reconstruct_official_export_fixture,
    verify_immutable_export_members,
    verify_immutable_export_zip,
)
from .http_client import (
    KBHTTPClientError,
    KBHTTPConfigurationError,
    KBHTTPContractError,
    KBHTTPExecutor,
    KBHTTPRawResponse,
    KBHTTPRequest,
    KBHTTPResponseError,
    KBHTTPTransportError,
    KBReadOnlyHTTPClient,
    UrllibKBHTTPExecutor,
    VerifiedHTTPArtifact,
    VerifiedHTTPDocument,
    VerifiedHTTPReleaseBundle,
)
from .provider_canonical import (
    CANONICALIZATION_PROFILE,
    ProviderCanonicalError,
    canonical_json_bytes,
    canonical_jsonl_bytes,
    manifest_sha256,
    sealed_manifest_bytes,
)
from .reference_fixture import (
    CONSUMER_CONTRACT_VERSION,
    CONTEXT_PACK_PROJECTION_VERSION,
    ReferenceFixtureError,
    ReferenceFixtureResult,
    ReferenceValidationCode,
    ValidatedArtifact,
    ValidatedChange,
    ValidatedRelease,
    verify_stage6_reference_fixture,
)
from .transport import (
    KBTransportCapability,
    KBTransportNotSupportedError,
    TransportSupportStatus,
    kb_transport_capabilities,
    require_supported_kb_transport,
)
from .transport_contracts import (
    HTTP_ENVELOPE_ID,
    HTTP_ERROR_ID,
    IMMUTABLE_EXPORT_ID,
    RELEASE_STATUS_HISTORY_ID,
    TRANSPORT_SNAPSHOT_LOCK_SHA256,
    TRANSPORT_SOURCE_COMMIT,
    KBTransportContractCatalog,
    load_kb_transport_contract_snapshot,
)

__all__ = [
    "CANONICALIZATION_PROFILE",
    "CONSUMER_CONTRACT_VERSION",
    "CONTEXT_PACK_PROJECTION_VERSION",
    "ContractSnapshotError",
    "ContractValidationError",
    "ExportValidationCode",
    "HTTP_ENVELOPE_ID",
    "HTTP_ERROR_ID",
    "IMMUTABLE_EXPORT_ID",
    "ImmutableExportValidationError",
    "KBContractCatalog",
    "KBHTTPClientError",
    "KBHTTPConfigurationError",
    "KBHTTPContractError",
    "KBHTTPExecutor",
    "KBHTTPRequest",
    "KBHTTPRawResponse",
    "KBReadOnlyHTTPClient",
    "KBHTTPResponseError",
    "KBHTTPTransportError",
    "KBTransportContractCatalog",
    "KBTransportCapability",
    "KBTransportNotSupportedError",
    "ProviderCanonicalError",
    "ReferenceFixtureError",
    "ReferenceFixtureResult",
    "ReferenceValidationCode",
    "RELEASE_STATUS_HISTORY_ID",
    "SnapshotIntegrityError",
    "StrictJsonError",
    "TransportSupportStatus",
    "TRANSPORT_SOURCE_COMMIT",
    "TRANSPORT_SNAPSHOT_LOCK_SHA256",
    "UrllibKBHTTPExecutor",
    "ValidatedArtifact",
    "ValidatedChange",
    "ValidatedRelease",
    "VerifiedExportMember",
    "VerifiedHTTPArtifact",
    "VerifiedHTTPDocument",
    "VerifiedHTTPReleaseBundle",
    "VerifiedImmutableExport",
    "canonical_json_bytes",
    "canonical_jsonl_bytes",
    "load_kb_contract_snapshot",
    "load_kb_transport_contract_snapshot",
    "load_strict_json_bytes",
    "manifest_sha256",
    "kb_transport_capabilities",
    "require_supported_kb_transport",
    "reconstruct_official_export_fixture",
    "sealed_manifest_bytes",
    "verify_stage6_reference_fixture",
    "verify_immutable_export_members",
    "verify_immutable_export_zip",
]
