"""Provider-neutral Stage 2B-0 strategy-domain contracts."""

from .replay import (
    REPLAY_CANONICAL_PROFILE_VERSION,
    REPLAY_ENVELOPE_SCHEMA_VERSION,
    ReplayEnvelope,
    ReplayValidationError,
    compute_replay_hash,
    verify_replay_hash,
)
from .rule_approval import (
    CURRENT_RULE_APPROVAL_REGISTRY,
    RULE_APPROVAL_RECORD_SCHEMA_VERSION,
    RULE_BUNDLE_DOCUMENT_SCHEMA_VERSION,
    ApprovedRuleCapability,
    RuleApprovalError,
    RuleApprovalRecord,
    RuleApprovalRegistry,
    RuleApprovalScope,
    RuleBundleDocument,
    require_approved_rule_bundle,
    rule_approval_record_from_json_value,
    rule_bundle_document_from_json_value,
)
from .strategy_input import (
    SYNTHETIC_VALIDATION_INPUT_SCHEMA_VERSION,
    StrategyInputProvenance,
    SyntheticValidationInput,
)
from .synthetic_fixture import (
    FAILURE_INJECTION_REGISTRATION_SCHEMA_VERSION,
    SYNTHETIC_FIXTURE_REGISTRATION_SCHEMA_VERSION,
    SYNTHETIC_FIXTURE_REGISTRY_PROFILE,
    SYNTHETIC_FIXTURE_REGISTRY_SCHEMA_VERSION,
    ApprovedSyntheticFixtureCapability,
    FailureInjectionFixtureRegistration,
    SyntheticFixtureAuthorizationError,
    SyntheticFixtureCapabilityScope,
    SyntheticFixtureRegistration,
    SyntheticFixtureRegistry,
    failure_injection_registration_from_json_value,
    synthetic_fixture_registration_from_json_value,
)

__all__ = [
    "CURRENT_RULE_APPROVAL_REGISTRY",
    "FAILURE_INJECTION_REGISTRATION_SCHEMA_VERSION",
    "REPLAY_CANONICAL_PROFILE_VERSION",
    "REPLAY_ENVELOPE_SCHEMA_VERSION",
    "RULE_APPROVAL_RECORD_SCHEMA_VERSION",
    "RULE_BUNDLE_DOCUMENT_SCHEMA_VERSION",
    "SYNTHETIC_VALIDATION_INPUT_SCHEMA_VERSION",
    "SYNTHETIC_FIXTURE_REGISTRATION_SCHEMA_VERSION",
    "SYNTHETIC_FIXTURE_REGISTRY_PROFILE",
    "SYNTHETIC_FIXTURE_REGISTRY_SCHEMA_VERSION",
    "ApprovedRuleCapability",
    "ApprovedSyntheticFixtureCapability",
    "FailureInjectionFixtureRegistration",
    "ReplayEnvelope",
    "ReplayValidationError",
    "RuleApprovalError",
    "RuleApprovalRecord",
    "RuleApprovalRegistry",
    "RuleApprovalScope",
    "RuleBundleDocument",
    "StrategyInputProvenance",
    "SyntheticValidationInput",
    "SyntheticFixtureAuthorizationError",
    "SyntheticFixtureCapabilityScope",
    "SyntheticFixtureRegistration",
    "SyntheticFixtureRegistry",
    "compute_replay_hash",
    "failure_injection_registration_from_json_value",
    "require_approved_rule_bundle",
    "rule_approval_record_from_json_value",
    "rule_bundle_document_from_json_value",
    "synthetic_fixture_registration_from_json_value",
    "verify_replay_hash",
]
